### PR TITLE
Add grid lines with labels

### PR DESCRIPTION
**Pull request by trentpiercy**
I can add screenshots and code examples for the README but this should be all the code for proper grid lines and labels.

### CODE REVIEW

**Comment by xqwzts** [comment]
@trentpiercy Apologies, I'm not sure how this slipped through for so long! I'll take it for a quick test and merge it in over the weekend.

**Comment by Tushar1998** [comment]
I want to change the linecolour after it raises a certain value and return to original colour when comes down plzz help
Or i can call a function for this ??? plzz    help

**Comment by xqwzts** [comment]
Merged.

Sorry for the ridiculous delay, and thanks for the contribution.

If you have the time a README update would be appreciated.

**Comment by trentpiercy** [comment]
@xqwzts Done :) #15

**Pull request merged**
